pub mod app_state;
pub mod backup;
pub mod export;
pub mod font;
pub mod knowledge;
pub mod knowledge_type;
pub mod menu;
pub mod outline;
pub mod scene_image;
pub mod scene_knowledge;
pub mod scene_version;
pub mod search;
pub mod settings;
pub mod work;

pub fn handler() -> impl Fn(tauri::ipc::Invoke) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        settings::get_settings,
        settings::save_settings,
        app_state::get_selected_work_id,
        app_state::save_selected_work_id,
        app_state::clear_selected_work_id,
        app_state::get_selected_node,
        app_state::save_selected_node,
        app_state::get_expanded_chapters,
        app_state::save_expanded_chapters,
        app_state::delete_work_ui_state,
        app_state::get_panel_sizes,
        app_state::save_panel_sizes,
        app_state::get_inspector_collapsed,
        app_state::save_inspector_collapsed,
        app_state::get_inspector_sections,
        app_state::save_inspector_sections,
        app_state::get_inspector_section_order,
        app_state::save_inspector_section_order,
        app_state::get_split_view_direction,
        app_state::save_split_view_direction,
        app_state::get_split_view_ratio,
        app_state::save_split_view_ratio,
        app_state::get_split_view_panes,
        app_state::save_split_view_panes,
        app_state::get_sidebar_sections,
        app_state::save_sidebar_sections,
        app_state::get_sidebar_section_ratio,
        app_state::save_sidebar_section_ratio,
        app_state::get_inspector_tab,
        app_state::save_inspector_tab,
        work::list_works,
        work::create_work,
        work::delete_work,
        work::update_work_name,
        work::get_chapter_count,
        work::get_work,
        outline::get_work_outline,
        outline::update_chapter_sort_order,
        outline::update_scene_sort_order,
        outline::move_scene_to_chapter,
        outline::delete_chapter,
        outline::delete_scene,
        outline::restore_chapter,
        outline::restore_scene,
        outline::permanent_delete_chapter,
        outline::permanent_delete_scene,
        outline::update_chapter_title,
        outline::update_scene_title,
        outline::create_chapter,
        outline::create_scene,
        outline::get_scene,
        outline::get_scenes_by_chapter,
        outline::update_scene_content,
        outline::update_scene_synopsis,
        outline::update_scene_word_count,
        outline::search_scenes,
        outline::get_work_statistics,
        knowledge::get_knowledge,
        knowledge::get_knowledge_by_work,
        knowledge::get_knowledge_by_type,
        knowledge::create_knowledge,
        knowledge::update_knowledge_title,
        knowledge::update_knowledge_body,
        knowledge::update_knowledge_sort_order,
        knowledge::update_knowledge_type_id,
        knowledge::delete_knowledge,
        knowledge::search_knowledge,
        knowledge_type::get_knowledge_type,
        knowledge_type::get_knowledge_types_by_work,
        knowledge_type::create_knowledge_type,
        knowledge_type::update_knowledge_type,
        knowledge_type::update_knowledge_type_sort_order,
        knowledge_type::delete_knowledge_type,
        knowledge_type::ensure_default_knowledge_types,
        font::list_system_fonts,
        export::export_txt,
        export::export_docx,
        export::export_pdf,
        export::export_epub,
        export::generate_export_preview,
        backup::create_backup,
        backup::list_backups,
        backup::restore_backup,
        backup::delete_backup,
        backup::get_backup_dir_path,
        backup::restart_app,
        menu::set_scene_menus_enabled,
        menu::set_split_view_menu_enabled,
        search::search_project,
        search::replace_in_project,
        scene_version::create_scene_version,
        scene_version::get_scene_versions,
        scene_version::get_scene_version,
        scene_version::restore_scene_version,
        scene_version::update_scene_version_label,
        scene_version::delete_scene_version,
        scene_knowledge::get_scene_knowledge,
        scene_knowledge::link_knowledge_to_scene,
        scene_knowledge::unlink_knowledge_from_scene,
        scene_image::get_scene_images,
        scene_image::add_scene_image,
        scene_image::delete_scene_image,
        scene_image::update_scene_image_sort_order,
        scene_image::get_scene_image_path,
    ]
}
